<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <NoWarn>SYSLIB0014</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization/Resources/*.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RemuxForge.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win.slim" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.official.runtime.linux-x64.slim" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.linux-arm64" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.osx.x64" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.osx.arm64" Version="4.13.0.20260627" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RemuxForge.Vulkan\RemuxForge.Vulkan.csproj" />
  </ItemGroup>

</Project>
